language: python

cache: pip

python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'

install:
- make install
- pip freeze

script:
- make lint
- make test
- ./tests/check_tag.py

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: pypi
  user: samuelcolvin
  password:
    secure: "tE/E8Fr8L4aILpfRFgHgc0YT0QUWMYPtbmckpCDU+Xa9p6sov4zo30s1ODKwSEuNxHf7qr91txWbT2JT1u8rMQcC172Crkroin39D+hQmYjyT4WPj8y8yBGoIs2EG6AaX3t43L5qs1pT99neKrsuy6uhmaWA7LsSN2OjgcpRFBLtGocTDyAH+qoZ02IpyzWe2vxaEJTMjoDyYyLp6f3U7rycrwEzUeN6bnYERc6VdW8idfMTgftcS2wXkCj7kyLZy9w9MciWPq5phPoPvE9zHpfvOLb/h8N/iPJsC293k5RQdiyFAul+IVkEa8bnHPIKjjgXsqNaqTBhV94SURLccb7Bd+jiQjexLtXio2mHXadUpT0UKUvm7DQHa8PqsMms7HS2X7cUkicAnbVU+kPJr7ba/Lr0OGj05ZVXS7wIaJFYI5wiQ5ucnl1CAOUk1LHHGaVOtfj2VMWPETfLN4z03ugwAeT2PDsttOpxowKVRWV1jNT9ldirFg7HJFi3+qzvXWTRTY10yt05MPZ2hL/+L5dExGVUxz6IhVf2UIAklzQgUpTsJrihKigRulxjpu44G0sHBNiRrCQq1tfNMNXcKvjx3t/IApv2KqmMc0PVQrTtlImQqyoOO/MaHRZKWAuu1itva+vuoR68n7g96+X4wUm7Ca4wTV83e0VefyFevGk="
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python: 3.7
