name: Bug
description: Report a bug or unexpected behavior in watchfiles
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in watchfiles! ðŸ˜Ž

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. ðŸ™

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please explain what you're seeing and what you expect to see.

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

        **Alternatively**, you might find it useful to run

        ```bash
        watchfiles 'echo reloaded' . --verbose
        ```

        and copy the output below.

      placeholder: |
        import watchfiles

        print(f'Watchfiles v{watchfiles.__version__}')
        for changes in watchfiles.watch('.', debug=True):
            print(changes)
      render: Python

  - type: textarea
    id: output
    attributes:
      label: Watchfiles Output
      description: Output from the above example code or `watchfiles 'echo reloaded' . --verbose`
      render: Text

  - type: textarea
    id: os
    attributes:
      label: Operating System & Architecture
      description: |
        What operating system version and system architecture are you using?

        ```bash
        python -c 'import platform; print(platform.platform()); print(platform.version())'
        ```
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      description: >
        Are you using a specific environment like docker, WSL, etc.?
        Also if you installed watchfiles or python in an unusual way.

  - type: input
    id: python-watchfiles-version
    attributes:
      label: Python & Watchfiles Version
      description: |
        Which version Python and Watchfiles are you using?

        ```bash
        python -c 'import sys, watchfiles; print(f"python: {sys.version}, watchfiles: {watchfiles.__version__}")'
        ```
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust & Cargo Version
      description: |
        If you're building watchfiles locally, which Rust and Cargo version are you using?

        ```bash
        cargo --version
        rustc --version
        ```
