name: Bug
description: Report a bug or unexpected behavior in watchfiles
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in watchfiles! 😎

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please explain what you're seeing and what you expect to see.

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

        **Note:** you will probably want to run `watchfiles` with `debug=True` to get more information about what's going on.

      placeholder: |
        from watchfiles import watch

        for changes in watch('.', debug=True):
            print(changes)
      render: Python

  - type: textarea
    id: output
    attributes:
      label: Example Code Output
      description: Output from the above example code.
      render: Text

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What Operating System version are you using? Also are you using a specific environment like docker?
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      description: >
        Are you using a specific environment like docker, WSL, etc.?
        Also if you installed watchfiles or python in an unusual way.

  - type: input
    id: watchfiles-version
    attributes:
      label: Watchfiles Version
      description: |
        Which `watchfiles` version are you using?

        ```bash
        python -c 'import watchfiles; print(watchfiles.__version__)'
        ```
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: |
        Which Python version are you using?

        ```bash
        python --version
        ```
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust & Cargo Version
      description: |
        If you're building watchfiles locally, which Rust and Cargo version are you using?

        ```bash
        cargo --version
        rustc --version
        ```
