[tool.poetry]
name = "watchman"
version = "0.0.1"
description = ""
authors = ["Samuel Colvin <s@muelcolvin.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
